### ISSUE TITLE
require('./style.css')

### ISSUE THREAD

**Issue by theskillwithin** [amurp/react-context-menu#2]
should not have require('./style.css'); in a node_module or else requires u to use a loader for your node_modules

**Comment by YouYue123** [comment]
Any update? I would like to make a pull request for this

**Comment by amurp** [comment]
Hi there - feel free to make a PR. 😃 

I can take a look later on if I don't hear back. This project is fairly old and I haven't had the time keep it in shape. It should be a very easy change.

**Comment by amurp** [comment]
Swapped out css import for inline styles.
