### ISSUE TITLE
Menu remains visible after option clicked

### ISSUE THREAD

**Issue by brendan-healey** [amurp/react-context-menu#5]
Hi, nice lightweight component really easy to use. I notice that the menu remains visible
after a menu option has been clicked and until the cursor is moved outside the menu area.
Should it not behave as per the bootstrap examples here?

https://getbootstrap.com/docs/4.3/components/dropdowns/

Thanks

**Comment by amurp** [comment]
Hey, thanks for the feedback. You can now pass ```closeOnClick``` (bool defaulted to false - original behavior unaffected) to the menu. Available now in 3.0.1.
